# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-07 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('schema_version', models.IntegerField()),
                ('outline_data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('context_key', opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('published_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearningSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='learning_sequences.LearningContext')),
            ],
        ),
        migrations.AddIndex(
            model_name='learningcontext',
            index=models.Index(fields=['-published_at'], name='learning_se_publish_62319b_idx'),
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='learning_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outline', to='learning_sequences.LearningContext'),
        ),
        migrations.AlterUniqueTogether(
            name='learningsequence',
            unique_together=set([('learning_context', 'usage_key')]),
        ),
    ]
