# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-07 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0002_auto_20200307_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='learning_context',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_outline', to='learning_sequences.LearningContext'),
        ),
        migrations.AlterField(
            model_name='learningcontext',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learningsequence',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
