# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-09 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0003_auto_20200307_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning_sequences.LearningContext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSectionSequences',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('learning_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_sequences', to='learning_sequences.LearningContext')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_sequences.CourseSection')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_sequences.LearningSequence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
