# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-10 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0004_coursesection_coursesectionsequences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSectionSequences',
            new_name='CourseSectionSequence',
        ),
        migrations.RemoveField(
            model_name='courseoutline',
            name='learning_context',
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together=set([('learning_context', 'usage_key')]),
        ),
        migrations.DeleteModel(
            name='CourseOutline',
        ),
    ]
