# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-11 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0005_auto_20200310_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
