# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-11 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0006_coursesection_order'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='coursesection',
            index_together=set([('learning_context', 'order')]),
        ),
        migrations.AlterIndexTogether(
            name='coursesectionsequence',
            index_together=set([('learning_context', 'order')]),
        ),
    ]
