# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0007_auto_20200311_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='created',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='coursesectionsequence',
            name='created',
        ),
        migrations.RemoveField(
            model_name='coursesectionsequence',
            name='modified',
        ),
    ]
