# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0009_auto_20200319_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='hide_from_toc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='visible_to_staff_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesectionsequence',
            name='hide_from_toc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesectionsequence',
            name='visible_to_staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
